In [1]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()  # 데이터셋을 가져왔을 때 다른 객체에 넣어주자.

In [2]:
print(cancer.data)
cancer.data.shape # 30개의 특성들로 이루어지고 569개의 샘플(환자) 수가 569개임

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


(569, 30)

In [3]:
print(cancer.target)
cancer.target.shape 
# 샘플(환자)수가 569개이듯 결과값 역시 569개
# 0은 음성(악성조양이 아님), 1은 양성(악성종양임)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

(569,)

In [4]:
x = cancer.data
y = cancer.target

In [5]:
import matplotlib.pyplot as plt
plt.figure(figsize = (10,7))
plt.boxplot(x)
plt.xlabel('feature', color = 'r')
plt.ylabel('value', color = 'r')
plt.xticks(color = 'r')
plt.yticks(color = 'r')
plt.show()

# 4, 14, 24 번째 feature값이 다양하다는 것을 알 수 있다.(분포가 크다)

<Figure size 1000x700 with 1 Axes>

In [6]:
cancer.feature_names[[3, 13, 23]]  
# 인덱스를 리스트를 사용해서 한꺼번에 준다.
# area에 관한 값들임을 알 수 있다.

array(['mean area', 'area error', 'worst area'], dtype='<U23')

In [7]:
import numpy as np

np.unique(y, return_counts = 'True')
# 0과 1로 이루어져있으며 0은 212개 1은 357개가 있다.

(array([0, 1]), array([212, 357], dtype=int64))

In [8]:
from sklearn.model_selection import train_test_split
# 샘플데이터와 타겟데이터를 훈련셋과 타겟셋으로 나누기 위한 함수.
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify = y, test_size = 0.2, random_state=42)
# stratify = y  -> y안에 0(음성클래스)와 1(양성클래스)가 있는데 모든세트의 비율 동일하게.

In [9]:
x_train.shape, x_test.shape

((455, 30), (114, 30))

In [10]:
y_train.shape, y_test.shape

((455,), (114,))

In [11]:
print(np.unique(y_train, return_counts = 'Ture')) 
# np.unique는 가지고 있는 요소들이 무엇인지 출력해주고
# return_counts = 'True' 를 주면 그 개수도 출력해준다.

np.unique(y_test, return_counts = 'True')

(array([0, 1]), array([170, 285], dtype=int64))


(array([0, 1]), array([42, 72], dtype=int64))

In [12]:
class LogisticNeuron:
    # 로지스틱함수를 쓰는 뉴런임.
    
    def __init__(self):
        self.w = None
        self.b = None
        # 입력 데이터의 특성이 많아 가중치를 미리 초기화하지 않는다.
        # 여기서 의문점은 어짜피 self.w와 self.b에 None을 줄껀데 __init__왜 필요한가이다.
        # 클래스를 만들때 __init__항상 들어가는데 정확한 기능을 잘 모르겠으니 찾아보자.
        
    def forpass(self, x): 
        # x는 계속 데이터에서 뽑는 변수 -> 파라미터
        # self.w 와 self,b 는 업데이트되는 친구들.(__init__안에 들어가는 것은 파라미터 불가능?)
        # 정방향. 첫 번째 단계는 가중치*특성값 과 절편을 넣어서 z를 뽑는 것.
        z = np.sum(x * self.w) + self.b
        return z # fit함수에 쓸것이므로 return z를 주자.
    
    def activation(self, z):
        a = 1 / (1 + np.exp(-z)) 
        # 시그모이트 함수 사용 
        # a를 0과 1사이의 확률로 갖도록 하기위해
        # 이 a가 특정 % 이상이면 1(양성) 아니면 0(음성)
        return a
    
    def backprop(self, x, err):
        w_grad = -x * err
        b_grad = -1 * err
        return w_grad, b_grad
    
    def fit(self, x, y, epochs = 100):
        self.w = np.ones(x.shape[1])
        self.b = 0
        for i in range(epochs):
            for x_i, y_i in zip(x, y):
                    z = self.forpass(x_i) 
                    # x_1은 30개의 특성값을 가진 샘플이라는 것을 기억하자
                  
                    a = self.activation(z)
                    err = y_i - a
                    # 언뜻보면 타겟값 1 또는 0 에서 0과 1사이의 확률를 빼는게 무슨 의마가
                    # 있는가 싶지만 이것은 로지스틱함수를 미분한값의 부분일 뿐!
                    
                    w_grad, b_grad = self.backprop(x_i, err)
                    self.w = self.w - w_grad
                    self.b = self.b - b_grad
                    
    def predict(self, x):
        z = [self.forpass(x_i) for x_i in x]
        a = self.activation(np.array(z))
        return a > 0.5

In [17]:
neuron = LogisticNeuron()
neuron.fit(x_train, y_train)
neuron.predict(x_test)

np.mean(neuron.predict(x_test) == y_test)

0.8245614035087719